modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Wulian233/Chat-Impressive-Animation/issues"
license = "MIT"

[[mods]]
modId = "chatimpressiveanimation"
version = "${version}"
displayName = "Chat Impressive Animation"
displayURL = "https://github.com/Wulian233/Chat-Impressive-Animation"
authors = "Wulian233, TexTrue"
description = '''
This mod makes the chat look better by adding animations. Such as opening chat, sending messages. It also removes the message indicator.
'''
logoFile = "icon.png"

[[mixins]]
config = "chatimpressiveanimation.mixins.json"

[[mixins]]
config = "chatimpressiveanimation.neoforge.mixins.json"

[[dependencies.chatimpressiveanimation]]
modId = "neoforge"
type = "required"
versionRange = "[20.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chatimpressiveanimation]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chatimpressiveanimation]]
modId = "cloth_config"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
